name: chrisburgess
favicon: null
layout_spectrum: 0.51083
typography_spectrum: 1
title: Chris Burgess
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.1875
  lightness: 0.6571106407791376
  saturation: 0.1052611623890698
  rhythmicContrast: 0.09195199399255216
purpose: []
